### ISSUE TITLE
The MASKER_DR Dataset

### ISSUE THREAD

**Issue by wangxuanx** [ispc-lab/GSC#1]
Hello, may I ask how the MASKER_MD data was obtained?

**Comment by TianhangWang** [comment]
Hi, thanks for your interest in our work. Actually, we utilize the [MMTracking](https://github.com/open-mmlab/mmtracking) to obtain the agent spatial state in scene. Then, please kindly refer to the https://github.com/ispc-lab/GSC/blob/main/scripts/preprecess_data_MASKER_MD.py (this code shows how to generate the MASKER_MD dataset step by step). Note that the Line 12 `data_root ='/media/group1/data/tianhang/sorted_samples_pn_2048/' `  in `preprecess_data_MASKER_MD.py ` is the folder that we store the spatial state by MMTracking. If you don't want to utilize the MMTracking, here is the corresponding [sorted_samples_pn_2048](https://pan.baidu.com/s/1UAJGloRquMU9ADV5GDR0Ig) processed by us. [password:tyk1]

**Comment by wangxuanx** [comment]
Thank you very much for your answer! : )
