### ISSUE TITLE
MMTracking使用的Model及如何获得的Feature

### ISSUE THREAD

**Issue by 1211186431** [ispc-lab/GSC#2]
你好，你们的工作很有价值，并且很吸引我们，我们注意到使用MMTracking来提取特征，但是，我们不太清楚具体使用的Model，以及如何获得的feature，希望能够尽快获得解答，谢谢！

**Comment by TianhangWang** [comment]
您好，非常感谢您对我们工作感兴趣，我们是按照 MMTracking 的官方教程进行特征提取的，具体流程您可以详细参考 MMTracking 的[官方文档](https://github.com/open-mmlab/mmtracking)。由于我们的使用MMTracking的是2021年份的版本，其对应的检测性能已经没有23年版本性能更好了，所以我们还是推荐您按照现有的 MMTracking 教程进行对应的特征提取。如果您还是更愿意使用我们基于21版MMTracking提取的特征，可以在此处下载[issue1](https://github.com/ispc-lab/GSC/issues/1#issuecomment-1537950307)。
